
package com.cxf.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceInterface", targetNamespace = "http://weathde.cxf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://weathde.cxf.com/", className = "com.cxf.weather.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://weathde.cxf.com/", className = "com.cxf.weather.QueryWeatherResponse")
    public String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
